import { PassCategory, PassTemplate, TicketCanvasThemeId } from '../types';

export interface CanvasThemeDefinition {
  id: TicketCanvasThemeId;
  name: string;
  tagline: string;
  badgeText: string;
  categoryDefault: PassCategory;
  bgClass: string;
  accentClass: string;
  borderClass: string;
  previewGradient: string;
  thumbnailStyle: string;
  description: string;
}

export const CANVAS_THEMES: Record<TicketCanvasThemeId, CanvasThemeDefinition> = {
  gold_foil_vip: {
    id: 'gold_foil_vip',
    name: 'Gold Foil VIP Pass',
    tagline: 'World Cup Trophy Edition',
    badgeText: 'VIP PASS',
    categoryDefault: 'courtside_vip',
    bgClass: 'from-amber-950 via-zinc-950 to-amber-900',
    accentClass: '#f59e0b',
    borderClass: 'border-amber-400/80',
    previewGradient: 'bg-gradient-to-r from-amber-500 via-yellow-600 to-amber-700',
    thumbnailStyle: 'Gold Leaf Metallic with Vertical VIP Ribbon & Trophy',
    description: 'Ultra-luxurious gold leaf foil pass with vertical ribbon, golden trophy accents, and high-security QR stub.',
  },
  purple_gold_sports: {
    id: 'purple_gold_sports',
    name: 'Sports All-Stars Tournament',
    tagline: 'Purple & Gold Stub Edition',
    badgeText: 'SPORT EVENT',
    categoryDefault: 'vip',
    bgClass: 'from-purple-950 via-indigo-950 to-purple-900',
    accentClass: '#eab308',
    borderClass: 'border-purple-400/70',
    previewGradient: 'bg-gradient-to-r from-purple-700 via-indigo-800 to-yellow-500',
    thumbnailStyle: 'Vibrant Deep Purple & Gold 3D Sports Lettering',
    description: 'Electric royal purple stub ticket featuring bold 3D sports lettering, seat/gate boxes, and tear-off barcode stub.',
  },
  neon_esports: {
    id: 'neon_esports',
    name: 'Esports Gaming Champion',
    tagline: 'Cyber Neon Crimson Edition',
    badgeText: 'GAMING CHAMPION',
    categoryDefault: 'courtside_floor',
    bgClass: 'from-rose-950 via-slate-950 to-red-950',
    accentClass: '#f43f5e',
    borderClass: 'border-rose-500/80',
    previewGradient: 'bg-gradient-to-r from-rose-700 via-red-900 to-rose-600',
    thumbnailStyle: 'Dark Crimson & Neon Pink Block Typography',
    description: 'High-octane tournament pass with notch cutouts, team vs team banner, and barcode ticket stub.',
  },
  sleek_black_match: {
    id: 'sleek_black_match',
    name: 'Sleek Black Match Day',
    tagline: 'Minimalist Matte Gold Edition',
    badgeText: 'MATCH TICKET',
    categoryDefault: 'general_access',
    bgClass: 'from-zinc-950 via-slate-950 to-zinc-900',
    accentClass: '#d97706',
    borderClass: 'border-amber-500/50',
    previewGradient: 'bg-gradient-to-r from-zinc-800 via-zinc-900 to-amber-600',
    thumbnailStyle: 'Matte Black & Gold Line Stadium Ticket',
    description: 'Sleek matte black ticket with gold trophy silhouette, match day stats, and tear-off barcode stub.',
  },
  courtside_classic: {
    id: 'courtside_classic',
    name: 'Courtside Official Credential',
    tagline: 'Liberia Arena VIP Edition',
    badgeText: 'COURTSIDE PASS',
    categoryDefault: 'courtside_vip',
    bgClass: 'from-blue-950 via-slate-900 to-red-950',
    accentClass: '#3b82f6',
    borderClass: 'border-blue-500/60',
    previewGradient: 'bg-gradient-to-r from-blue-700 via-slate-800 to-red-600',
    thumbnailStyle: 'Official Blue & Red Hologram Security Credential',
    description: 'Official Courtside Liberia digital pass with metallic header, section matrix, and encrypted security QR code.',
  },
};

export const PASS_TEMPLATES: Record<PassCategory, PassTemplate> = {
  courtside_vip: {
    id: 'tpl_courtside_vip',
    name: 'Courtside Ultra VIP',
    category: 'courtside_vip',
    bgGradient: 'from-blue-950 via-slate-900 to-red-950',
    badgeBg: 'bg-blue-500/20 text-blue-300 border-blue-400/40',
    badgeText: 'COURTSIDE VIP',
    borderColor: 'border-blue-500/40',
    accentColor: '#3b82f6',
    glowColor: 'rgba(59, 130, 246, 0.25)',
    description: 'Front row courtside experience with exclusive lounge, valet & open bar.',
  },
  regular: {
    id: 'tpl_regular',
    name: 'Regular Admission',
    category: 'regular',
    bgGradient: 'from-blue-950 via-slate-900 to-slate-950',
    badgeBg: 'bg-blue-500/20 text-blue-300 border-blue-400/40',
    badgeText: 'REGULAR',
    borderColor: 'border-blue-500/40',
    accentColor: '#3b82f6',
    glowColor: 'rgba(59, 130, 246, 0.25)',
    description: 'Standard event admission access.',
  },
  vip: {
    id: 'tpl_vip',
    name: 'VIP Executive',
    category: 'vip',
    bgGradient: 'from-amber-950 via-slate-900 to-yellow-950',
    badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-400/40',
    badgeText: 'VIP PASS',
    borderColor: 'border-amber-500/40',
    accentColor: '#f59e0b',
    glowColor: 'rgba(245, 158, 11, 0.25)',
    description: 'Premium elevated seating with fast track entry and catering.',
  },
  vvip: {
    id: 'tpl_vvip',
    name: 'VVIP Courtside',
    category: 'vvip',
    bgGradient: 'from-purple-950 via-slate-950 to-amber-950',
    badgeBg: 'bg-amber-400/30 text-amber-300 border-amber-400/80',
    badgeText: 'VVIP ACCESS',
    borderColor: 'border-amber-400',
    accentColor: '#f59e0b',
    glowColor: 'rgba(245, 158, 11, 0.35)',
    description: 'Ultra-exclusive VVIP admission with all-access privileges.',
  },
  all_access: {
    id: 'tpl_all_access',
    name: 'All Access Pass',
    category: 'all_access',
    bgGradient: 'from-emerald-950 via-slate-950 to-red-950',
    badgeBg: 'bg-emerald-500/30 text-emerald-300 border-emerald-400/80',
    badgeText: 'ALL ACCESS',
    borderColor: 'border-emerald-400',
    accentColor: '#10b981',
    glowColor: 'rgba(16, 185, 129, 0.35)',
    description: 'Full facility and back-of-house all-access credential.',
  },
  courtside_box: {
    id: 'tpl_courtside_box',
    name: 'Courtside Box Suite',
    category: 'courtside_box',
    bgGradient: 'from-blue-950 via-slate-900 to-slate-950',
    badgeBg: 'bg-blue-500/20 text-blue-300 border-blue-400/40',
    badgeText: 'BOX SUITE',
    borderColor: 'border-blue-500/40',
    accentColor: '#3b82f6',
    glowColor: 'rgba(59, 130, 246, 0.25)',
    description: 'Private luxury box for group hosting right next to team bench.',
  },
  courtside_floor: {
    id: 'tpl_courtside_floor',
    name: 'Courtside Floor Access',
    category: 'courtside_floor',
    bgGradient: 'from-rose-950 via-slate-900 to-red-950',
    badgeBg: 'bg-rose-500/20 text-rose-300 border-rose-400/40',
    badgeText: 'FLOOR PASS',
    borderColor: 'border-rose-500/40',
    accentColor: '#f43f5e',
    glowColor: 'rgba(244, 63, 94, 0.25)',
    description: 'Floor level access with sideline seats and halftime tunnel walk.',
  },
  general_access: {
    id: 'tpl_general_access',
    name: 'General Access',
    category: 'general_access',
    bgGradient: 'from-blue-950 via-slate-900 to-slate-950',
    badgeBg: 'bg-blue-500/20 text-blue-300 border-blue-400/40',
    badgeText: 'STANDARD PASS',
    borderColor: 'border-blue-500/40',
    accentColor: '#3b82f6',
    glowColor: 'rgba(59, 130, 246, 0.25)',
    description: 'Standard stadium tier seating with access to fan concessions.',
  },
  media: {
    id: 'tpl_media',
    name: 'Press & Media Credential',
    category: 'media',
    bgGradient: 'from-sky-950 via-slate-900 to-slate-900',
    badgeBg: 'bg-sky-500/20 text-sky-300 border-sky-400/40',
    badgeText: 'PRESS / MEDIA',
    borderColor: 'border-sky-500/40',
    accentColor: '#0ea5e9',
    glowColor: 'rgba(14, 165, 233, 0.25)',
    description: 'Press row access, post-match conference hall, and photo deck.',
  },
  player_staff: {
    id: 'tpl_player_staff',
    name: 'Player & All-Access Staff',
    category: 'player_staff',
    bgGradient: 'from-red-950 via-slate-900 to-blue-950',
    badgeBg: 'bg-red-500/20 text-red-300 border-red-400/40',
    badgeText: 'ALL ACCESS / STAFF',
    borderColor: 'border-red-500/40',
    accentColor: '#ef4444',
    glowColor: 'rgba(239, 68, 68, 0.25)',
    description: 'Locker room, team bench, referee tunnel and back-of-house areas.',
  },
};

export const DEFAULT_EVENT_INFO = {
  eventName: '',
  venue: '',
  eventDate: '',
  eventTime: '18:00 GMT',
  currency: 'USD',
};
